INSERT INTO PROJECTS VALUES(1,'PHPixie PHP Framework','PHPixie','PHPixie started as a micro framework and has gradually grown');

INSERT INTO EMPLOYEES VALUES(1,'Buckland','Adam','Bernadette','Software Engineer';
INSERT INTO EMPLOYEES VALUES(2,'Anna','Cameron','Bower','Test Software Programmer');
INSERT INTO EMPLOYEES VALUES(3,'Elizabeth','Christopher','Carr','Entry Level Programmer');
INSERT INTO EMPLOYEES VALUES(4,'Lawrence','MacDonald','Johnston','Java Developer');
INSERT INTO EMPLOYEES VALUES(5,'Rebecca','Manning','Kerr','Web Programmer');

INSERT INTO TASKS VALUES(1,'Developemt Phase',260,'1970-01-01','1970-01-01','INPROGRESS','PHPixie');
INSERT INTO TASKS VALUES(2,'Deploy application',100,'1970-01-01','1970-01-01','NOTSTARTED','PHPixie');
INSERT INTO TASKS VALUES(3,'Gather Requirements',50,'1970-01-01','1970-01-01','COMPLETED','PHPixie');

INSERT INTO REFLIST_PROJ VALUES(68,1,1);
INSERT INTO REFLIST_PROJ VALUES(69,1,2);
INSERT INTO REFLIST_PROJ VALUES(70,1,3);

INSERT INTO REFLIST_EMPL VALUES(178,1,1);
INSERT INTO REFLIST_EMPL VALUES(179,3,1);
INSERT INTO REFLIST_EMPL VALUES(180,4,2);
INSERT INTO REFLIST_EMPL VALUES(181,5,2);
INSERT INTO REFLIST_EMPL VALUES(182,3,3);
INSERT INTO REFLIST_PROJ VALUES(68,1,1);
INSERT INTO REFLIST_PROJ VALUES(69,1,2);
INSERT INTO REFLIST_PROJ VALUES(70,1,3);
INSERT INTO REFLIST_PROJ VALUES(71,1,1);
INSERT INTO REFLIST_PROJ VALUES(72,1,2);
INSERT INTO REFLIST_PROJ VALUES(73,1,3);